### ISSUE TITLE
Realy open source?

### ISSUE THREAD

**Issue by Hexodus** [jonathanbertholet/promptmanager#4]
I tried this extension today and found a small bug I wanted to fix. There's where I realized that cloning the project don't get me all the needed files to do so. That's a surprise. So what's the deal with it?

**Comment by jonathanbertholet** [comment]
Hi @Hexodus !

If a file is missing, it must've been an oversight!
I'll update the source code shortly :) 

Out of curiosity, what's the bug you've found?

Thanks!!

**Comment by Hexodus** [comment]
Hi Jonathan, bug or expected behavior, I can't tell exactly. But the line breaks of a saved prompt don't translate into line breaks in chatgpt and cloude.

**Comment by jonathanbertholet** [comment]
Ah, yes. 

I'm not sure how to classify the issue. I suspect ChatGPT has some form of sanitizing going on in their input area that others (e.g. Gemini) don't have. 

I haven't considered it a priority to fix it, since it doesn't seem to affect prompt performance as far as I know, but I acknowledge it can be tricky if using variables. 

Also - apologies about the source code. I didn't have time yesterday, will be fixed today!

**Comment by jonathanbertholet** [comment]
Hi @Hexodus 

Source code updated! Note that the icons are missing - I'm not sure I can actually distribute them without issues, perhaps you can use placeholder icons? Compiling the extension in Chrome might not work since the manifest file references them.

**Comment by Hexodus** [comment]
Hi Jonathan,
thanks for the update. I created the pull request so take a look there.
Not sure why you're concerned about the icons. They look pretty generic to me. You're aware that whoever installs the extension has your full code and icons on their PC? And that's where I've got them from. So you allready distribute them. 
Point is that partial repos are a pain to work with.

**Comment by jonathanbertholet** [comment]
Thanks a lot! It's super appreciated!

Oops, understood, and thank you! It's my first project, so I'm not entirely familiar with some of the best practices and limitations, and I am trying to play it safe. 

I'll confirm that PR asap, then publish the update to the chrome store.

**Comment by jonathanbertholet** [comment]
Hi @Hexodus 

Published for review to the chrome web store :) added a special thanks to you to the release notes :) 

Thanks again!

**Comment by Hexodus** [comment]
Oh wow, I haven't expacted that - thanks! And I'm glad I could help. Especially because I like your project very mutch.
